name: Next Release

on:
  workflow_run:
    workflows:
      - Continuous Integration
    branches:
      - main
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-20.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: shabados/actions/setup-git-identity@release/next
        with:
          user: Shabad OS Bot
          email: team@shabados.com

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: shabados/actions/bump-version@release/next
        with:
          prerelease: next

      - uses: c-hive/gha-npm-cache@v1

      - run: npm install

      - run: npm run build

      - uses: shabados/actions/publish-github@release/next
        with:
          github_token: ${{ secrets.GH_BOT_TOKEN }}

      - uses: shabados/actions/publish-branch@release/next
        with:
          gitignore: |
            !dist/
